- name: Demo on Variables
  hosts: localhost
  vars:
    URL: play.example.com
  tasks:
    - name: Play Level URL
      ansible.builtin.debug:
        msg: URL - {{ URL }}
    - name: Task level URL
      vars:
        URL: task.example.com
      ansible.builtin.debug:
        msg: URL - {{ URL }}
- name: Load vars from a file
  hosts: all
  vars_files:
    - exvars.yml
  # vars_file is not supported in tasks. It is only supported at play level
  tasks:
    - name: Print URL
      ansible.builtin.debug:
        msg: URL - {{ URL }}

- name: Roles vars
  hosts: all
  vars:
    URL_PLAY: role_play.example.com
  roles:
    - sample
- name: Load vars from a file
  hosts: all
  tasks:
    - name: Run uptime command using shell
      ansible.builtin.shell: uptime
      register: output
    - name: Print output
      ansible.builtin.debug:
        msg: '{{ output.start }}'
