- name: Demo on Variables
  hosts: all
  vars:
    URL: play.example.com
  tasks:
    - name: Play Level URL
      ansible.builtin.debug:
        msg: URL - {{ URL }}
    - name: Task level URL
      vars:
        URL: task.example.com
      ansible.builtin.debug:
        msg: URL - {{ URL }}